CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, full_name TEXT, role TEXT NOT NULL DEFAULT 'RECEPTIONIST', active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS departments (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, description TEXT);
CREATE TABLE IF NOT EXISTS doctors (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, specialization TEXT, phone TEXT, email TEXT, department_id INTEGER, available INTEGER NOT NULL DEFAULT 1, FOREIGN KEY (department_id) REFERENCES departments(id));
CREATE TABLE IF NOT EXISTS patients (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, age INTEGER, gender TEXT, phone TEXT, email TEXT, address TEXT, blood_group TEXT, registered_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS appointments (id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id INTEGER NOT NULL, doctor_id INTEGER NOT NULL, appointment_date TEXT NOT NULL, time_slot TEXT NOT NULL, reason TEXT, status TEXT NOT NULL DEFAULT 'SCHEDULED', notes TEXT, created_at TEXT DEFAULT (datetime('now')), FOREIGN KEY (patient_id) REFERENCES patients(id), FOREIGN KEY (doctor_id) REFERENCES doctors(id));
CREATE TABLE IF NOT EXISTS emergency_queue (id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id INTEGER NOT NULL, priority INTEGER NOT NULL DEFAULT 3, description TEXT, status TEXT NOT NULL DEFAULT 'WAITING', arrived_at TEXT DEFAULT (datetime('now')), attended_at TEXT, FOREIGN KEY (patient_id) REFERENCES patients(id));
CREATE TABLE IF NOT EXISTS beds (id INTEGER PRIMARY KEY AUTOINCREMENT, bed_number TEXT NOT NULL UNIQUE, ward TEXT NOT NULL, patient_id INTEGER, status TEXT NOT NULL DEFAULT 'AVAILABLE', admitted_at TEXT, FOREIGN KEY (patient_id) REFERENCES patients(id));
CREATE TABLE IF NOT EXISTS lab_tests (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT, price REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS lab_orders (id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id INTEGER NOT NULL, test_id INTEGER NOT NULL, doctor_id INTEGER, ordered_at TEXT DEFAULT (datetime('now')), result TEXT, result_date TEXT, status TEXT NOT NULL DEFAULT 'PENDING', FOREIGN KEY (patient_id) REFERENCES patients(id), FOREIGN KEY (test_id) REFERENCES lab_tests(id), FOREIGN KEY (doctor_id) REFERENCES doctors(id));
CREATE TABLE IF NOT EXISTS bills (id INTEGER PRIMARY KEY AUTOINCREMENT, patient_id INTEGER NOT NULL, consultation_fee REAL NOT NULL DEFAULT 0, lab_charges REAL NOT NULL DEFAULT 0, bed_charges REAL NOT NULL DEFAULT 0, medicine_charges REAL NOT NULL DEFAULT 0, total REAL NOT NULL DEFAULT 0, payment_status TEXT NOT NULL DEFAULT 'UNPAID', payment_method TEXT, created_at TEXT DEFAULT (datetime('now')), FOREIGN KEY (patient_id) REFERENCES patients(id));

INSERT OR IGNORE INTO users(username,password_hash,full_name,role) VALUES('admin','240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9','Dr. Admin','ADMIN'),('receptionist','10176e7b7b24d317acfcf8d2064cfd2f24e154f7b5a96603077d5ef813d6a6b6','Staff User','RECEPTIONIST');
INSERT OR IGNORE INTO departments(name,description) VALUES('Cardiology','Heart and blood vessel diseases'),('Neurology','Brain and nervous system'),('Orthopedics','Bones and joints'),('Pediatrics','Children health'),('General Medicine','Common illnesses and checkups'),('Emergency','Critical and emergency care');
INSERT OR IGNORE INTO doctors(name,specialization,phone,email,department_id,available) VALUES('Dr. Rafiq Ahmed','Cardiologist','01711001001','rafiq@healthdesk.com',1,1),('Dr. Nusrat Jahan','Neurologist','01711002002','nusrat@healthdesk.com',2,1),('Dr. Kamal Hossain','Orthopedic Surgeon','01711003003','kamal@healthdesk.com',3,1),('Dr. Sadia Islam','Pediatrician','01711004004','sadia@healthdesk.com',4,1),('Dr. Rahim Uddin','General Physician','01711005005','rahim@healthdesk.com',5,1),('Dr. Fatema Khatun','Emergency Specialist','01711006006','fatema@healthdesk.com',6,1);
INSERT OR IGNORE INTO patients(name,age,gender,phone,email,address,blood_group) VALUES('Amir Hossain',45,'Male','01811001001','amir@email.com','Mirpur, Dhaka','A+'),('Rina Begum',32,'Female','01811002002','rina@email.com','Gulshan, Dhaka','O+'),('Karim Mia',60,'Male','01811003003','karim@email.com','Agrabad, Chittagong','B+'),('Shirin Akter',28,'Female','01811004004','shirin@email.com','Sylhet Sadar','AB+');
INSERT OR IGNORE INTO lab_tests(name,description,price) VALUES('Complete Blood Count','CBC blood test',500),('Blood Sugar Fasting','Fasting glucose test',200),('Chest X-Ray','Radiological chest examination',800),('ECG','Electrocardiogram heart test',600),('Urine Routine','Urine examination',300),('Liver Function Test','LFT panel',1200);
INSERT OR IGNORE INTO beds(bed_number,ward,status) VALUES('A-101','General Ward','AVAILABLE'),('A-102','General Ward','AVAILABLE'),('A-103','General Ward','AVAILABLE'),('B-201','Cardiology Ward','AVAILABLE'),('B-202','Cardiology Ward','AVAILABLE'),('C-301','ICU','AVAILABLE'),('C-302','ICU','AVAILABLE'),('D-401','Pediatrics Ward','AVAILABLE');
